import type { CardDefinition } from "@riftbound/shared";

// Generated from Mermaids-Giants-Terra_首批60张卡牌策划表.xlsx.
// Complex effects tagged PROTOTYPE retain their formal text but await a later rules-engine version.
export const CARD_DATABASE: readonly CardDefinition[] = [
  { id: "MER-M-001", nameKey: "mer_m_001_name", descriptionKey: "mer_m_001_description", type: "MINION", faction: "MERMAID", rarity: "COMMON", cost: 1, rune: "◉", deckLimit: 2, keywords: [], targetRule: "无需目标", implementationTags: ["battlecry", "tribe_check", "heal_hero"], species: "人鱼", attack: 1, health: 2 },
  { id: "MER-M-002", nameKey: "mer_m_002_name", descriptionKey: "mer_m_002_description", type: "MINION", faction: "MERMAID", rarity: "COMMON", cost: 1, rune: "◉", deckLimit: 2, keywords: [], targetRule: "无需目标", implementationTags: ["deathrattle", "generate_token", "cost_reduce"], species: "人鱼", attack: 2, health: 1 },
  { id: "MER-M-003", nameKey: "mer_m_003_name", descriptionKey: "mer_m_003_description", type: "MINION", faction: "MERMAID", rarity: "COMMON", cost: 2, rune: "◉", deckLimit: 2, keywords: ["HEAL", "GUARD"], targetRule: "无需目标", implementationTags: ["guard", "after_heal", "temp_attack"], species: "人鱼", attack: 2, health: 3 },
  { id: "MER-M-004", nameKey: "mer_m_004_name", descriptionKey: "mer_m_004_description", type: "MINION", faction: "MERMAID", rarity: "COMMON", cost: 2, rune: "◉", deckLimit: 2, keywords: [], targetRule: "无需目标", implementationTags: ["battlecry", "spell_discount"], species: "人鱼", attack: 2, health: 2 },
  { id: "MER-M-005", nameKey: "mer_m_005_name", descriptionKey: "mer_m_005_description", type: "MINION", faction: "MERMAID", rarity: "COMMON", cost: 2, rune: "◉", deckLimit: 2, keywords: ["DRAW"], targetRule: "无需目标", implementationTags: ["on_draw_spell", "gain_health"], species: "人鱼", attack: 3, health: 2 },
  { id: "MER-M-006", nameKey: "mer_m_006_name", descriptionKey: "mer_m_006_description", type: "MINION", faction: "MERMAID", rarity: "RARE", cost: 3, rune: "◉", deckLimit: 2, keywords: [], targetRule: "选择一个敌方随从", implementationTags: ["battlecry", "freeze_attack"], species: "人鱼", attack: 2, health: 4 },
  { id: "MER-M-007", nameKey: "mer_m_007_name", descriptionKey: "mer_m_007_description", type: "MINION", faction: "MERMAID", rarity: "COMMON", cost: 3, rune: "◉", deckLimit: 2, keywords: ["CHARGE"], targetRule: "选择一个敌方随从", implementationTags: ["rush", "damaged_target_bonus"], species: "人鱼", attack: 3, health: 3 },
  { id: "MER-M-008", nameKey: "mer_m_008_name", descriptionKey: "mer_m_008_description", type: "MINION", faction: "MERMAID", rarity: "RARE", cost: 3, rune: "◉", deckLimit: 2, keywords: ["DRAW"], targetRule: "无需目标", implementationTags: ["end_turn", "healed_this_turn", "draw"], species: "人鱼", attack: 2, health: 4 },
  { id: "MER-M-009", nameKey: "mer_m_009_name", descriptionKey: "mer_m_009_description", type: "MINION", faction: "MERMAID", rarity: "COMMON", cost: 3, rune: "◉", deckLimit: 2, keywords: ["GUARD"], targetRule: "无需目标", implementationTags: ["guard", "tribe_aura", "health_aura"], species: "人鱼", attack: 3, health: 4 },
  { id: "MER-M-010", nameKey: "mer_m_010_name", descriptionKey: "mer_m_010_description", type: "MINION", faction: "MERMAID", rarity: "RARE", cost: 4, rune: "◉", deckLimit: 2, keywords: [], targetRule: "无需目标", implementationTags: ["battlecry", "copy_last_spell", "generate_copy"], species: "人鱼", attack: 3, health: 4 },
  { id: "MER-M-011", nameKey: "mer_m_011_name", descriptionKey: "mer_m_011_description", type: "MINION", faction: "MERMAID", rarity: "COMMON", cost: 4, rune: "◉", deckLimit: 2, keywords: ["GUARD"], targetRule: "无需目标", implementationTags: ["battlecry", "summon_token", "guard"], species: "人鱼", attack: 4, health: 4 },
  { id: "MER-M-012", nameKey: "mer_m_012_name", descriptionKey: "mer_m_012_description", type: "MINION", faction: "MERMAID", rarity: "RARE", cost: 4, rune: "◉", deckLimit: 2, keywords: ["HEAL"], targetRule: "选择一个友方角色", implementationTags: ["battlecry", "heal", "overheal", "buff_attack"], species: "人鱼", attack: 3, health: 5 },
  { id: "MER-M-013", nameKey: "mer_m_013_name", descriptionKey: "mer_m_013_description", type: "MINION", faction: "MERMAID", rarity: "EPIC", cost: 5, rune: "◉", deckLimit: 2, keywords: ["CHARGE"], targetRule: "无需目标", implementationTags: ["conditional_rush", "on_kill", "heal_hero"], species: "人鱼", attack: 5, health: 4 },
  { id: "MER-M-014", nameKey: "mer_m_014_name", descriptionKey: "mer_m_014_description", type: "MINION", faction: "MERMAID", rarity: "RARE", cost: 5, rune: "◉", deckLimit: 2, keywords: [], targetRule: "无需目标", implementationTags: ["battlecry", "resurrect", "tribe_filter"], species: "人鱼", attack: 4, health: 6 },
  { id: "MER-M-015", nameKey: "mer_m_015_name", descriptionKey: "mer_m_015_description", type: "MINION", faction: "MERMAID", rarity: "EPIC", cost: 5, rune: "◉", deckLimit: 2, keywords: ["HEAL"], targetRule: "无需目标", implementationTags: ["after_hero_heal", "random_friendly_buff", "trigger_cap"], species: "人鱼", attack: 3, health: 7 },
  { id: "MER-M-016", nameKey: "mer_m_016_name", descriptionKey: "mer_m_016_description", type: "MINION", faction: "MERMAID", rarity: "RARE", cost: 6, rune: "◉", deckLimit: 2, keywords: [], targetRule: "无需目标", implementationTags: ["battlecry", "board_count", "tribe_buff"], species: "人鱼", attack: 5, health: 7 },
  { id: "MER-M-017", nameKey: "mer_m_017_name", descriptionKey: "mer_m_017_description", type: "MINION", faction: "MERMAID", rarity: "EPIC", cost: 6, rune: "◉", deckLimit: 2, keywords: ["GUARD"], targetRule: "无需目标", implementationTags: ["guard", "deathrattle", "aoe_heal_friendly"], species: "人鱼", attack: 4, health: 8 },
  { id: "MER-M-018", nameKey: "mer_m_018_name", descriptionKey: "mer_m_018_description", type: "MINION", faction: "MERMAID", rarity: "EPIC", cost: 7, rune: "◉", deckLimit: 2, keywords: [], targetRule: "无需目标", implementationTags: ["battlecry", "discover_history", "cost_set_zero"], species: "人鱼", attack: 6, health: 7 },
  { id: "MER-M-019", nameKey: "mer_m_019_name", descriptionKey: "mer_m_019_description", type: "MINION", faction: "MERMAID", rarity: "LEGENDARY", cost: 8, rune: "◉", deckLimit: 1, keywords: ["GUARD"], targetRule: "无需目标", implementationTags: ["legendary", "battlecry", "bounce_all", "heal_per_friendly"], species: "人鱼", attack: 7, health: 9 },
  { id: "MER-M-020", nameKey: "mer_m_020_name", descriptionKey: "mer_m_020_description", type: "MINION", faction: "MERMAID", rarity: "LEGENDARY", cost: 9, rune: "◉", deckLimit: 1, keywords: [], targetRule: "无需目标", implementationTags: ["legendary", "battlecry", "summon_tokens", "spell_trigger_buff"], species: "人鱼", attack: 8, health: 8 },
  { id: "GIA-M-001", nameKey: "gia_m_001_name", descriptionKey: "gia_m_001_description", type: "MINION", faction: "GIANT", rarity: "COMMON", cost: 1, rune: "◆", deckLimit: 2, keywords: [], targetRule: "无需目标", implementationTags: ["end_turn", "did_not_attack", "gain_attack"], species: "巨人", attack: 1, health: 3 },
  { id: "GIA-M-002", nameKey: "gia_m_002_name", descriptionKey: "gia_m_002_description", type: "MINION", faction: "GIANT", rarity: "COMMON", cost: 2, rune: "◆", deckLimit: 2, keywords: [], targetRule: "无需目标", implementationTags: ["attack_restriction", "tribe_check"], species: "巨人", attack: 2, health: 4 },
  { id: "GIA-M-003", nameKey: "gia_m_003_name", descriptionKey: "gia_m_003_description", type: "MINION", faction: "GIANT", rarity: "COMMON", cost: 2, rune: "◆", deckLimit: 2, keywords: [], targetRule: "选择一个友方随从", implementationTags: ["battlecry", "friendly_target", "buff_health"], species: "巨人", attack: 3, health: 2 },
  { id: "GIA-M-004", nameKey: "gia_m_004_name", descriptionKey: "gia_m_004_description", type: "MINION", faction: "GIANT", rarity: "COMMON", cost: 2, rune: "◆", deckLimit: 2, keywords: ["GUARD"], targetRule: "无需目标", implementationTags: ["guard", "start_turn", "self_heal"], species: "巨人", attack: 2, health: 3 },
  { id: "GIA-M-005", nameKey: "gia_m_005_name", descriptionKey: "gia_m_005_description", type: "MINION", faction: "GIANT", rarity: "COMMON", cost: 3, rune: "◆", deckLimit: 2, keywords: [], targetRule: "无需目标", implementationTags: ["battlecry", "look_top", "draw_big_minion"], species: "巨人", attack: 3, health: 4 },
  { id: "GIA-M-006", nameKey: "gia_m_006_name", descriptionKey: "gia_m_006_description", type: "MINION", faction: "GIANT", rarity: "RARE", cost: 3, rune: "◆", deckLimit: 2, keywords: ["DAMAGE", "GUARD"], targetRule: "无需目标", implementationTags: ["guard", "after_damaged", "gain_attack"], species: "巨人", attack: 2, health: 6 },
  { id: "GIA-M-007", nameKey: "gia_m_007_name", descriptionKey: "gia_m_007_description", type: "MINION", faction: "GIANT", rarity: "COMMON", cost: 3, rune: "◆", deckLimit: 2, keywords: ["DAMAGE"], targetRule: "选择一个敌方随从", implementationTags: ["battlecry", "damage", "damaged_target_bonus"], species: "巨人", attack: 4, health: 3 },
  { id: "GIA-M-008", nameKey: "gia_m_008_name", descriptionKey: "gia_m_008_description", type: "MINION", faction: "GIANT", rarity: "RARE", cost: 4, rune: "◆", deckLimit: 2, keywords: [], targetRule: "无需目标", implementationTags: ["tribe_aura", "attack_aura", "own_turn_only"], species: "巨人", attack: 3, health: 5 },
  { id: "GIA-M-009", nameKey: "gia_m_009_name", descriptionKey: "gia_m_009_description", type: "MINION", faction: "GIANT", rarity: "COMMON", cost: 4, rune: "◆", deckLimit: 2, keywords: ["GUARD"], targetRule: "无需目标", implementationTags: ["guard", "battlecry", "big_card_in_hand", "buff_health"], species: "巨人", attack: 3, health: 6 },
  { id: "GIA-M-010", nameKey: "gia_m_010_name", descriptionKey: "gia_m_010_description", type: "MINION", faction: "GIANT", rarity: "RARE", cost: 4, rune: "◆", deckLimit: 2, keywords: ["DAMAGE"], targetRule: "无需目标", implementationTags: ["end_turn", "did_not_attack", "random_enemy_damage"], species: "巨人", attack: 5, health: 4 },
  { id: "GIA-M-011", nameKey: "gia_m_011_name", descriptionKey: "gia_m_011_description", type: "MINION", faction: "GIANT", rarity: "RARE", cost: 5, rune: "◆", deckLimit: 2, keywords: [], targetRule: "无需目标", implementationTags: ["battlecry", "hand_highest_cost", "cost_reduce"], species: "巨人", attack: 4, health: 6 },
  { id: "GIA-M-012", nameKey: "gia_m_012_name", descriptionKey: "gia_m_012_description", type: "MINION", faction: "GIANT", rarity: "COMMON", cost: 5, rune: "◆", deckLimit: 2, keywords: ["CHARGE"], targetRule: "选择一个敌方随从", implementationTags: ["rush", "combat_survivor", "temp_attack_debuff"], species: "巨人", attack: 6, health: 5 },
  { id: "GIA-M-013", nameKey: "gia_m_013_name", descriptionKey: "gia_m_013_description", type: "MINION", faction: "GIANT", rarity: "EPIC", cost: 6, rune: "◆", deckLimit: 2, keywords: ["DAMAGE"], targetRule: "无需目标", implementationTags: ["after_damaged", "aoe_damage", "no_recursive_trigger"], species: "巨人", attack: 6, health: 7 },
  { id: "GIA-M-014", nameKey: "gia_m_014_name", descriptionKey: "gia_m_014_description", type: "MINION", faction: "GIANT", rarity: "RARE", cost: 6, rune: "◆", deckLimit: 2, keywords: ["CHARGE"], targetRule: "无需目标", implementationTags: ["battlecry", "summon_tokens", "rush"], species: "巨人", attack: 5, health: 7 },
  { id: "GIA-M-015", nameKey: "gia_m_015_name", descriptionKey: "gia_m_015_description", type: "MINION", faction: "GIANT", rarity: "EPIC", cost: 7, rune: "◆", deckLimit: 2, keywords: ["DAMAGE", "GUARD"], targetRule: "无需目标", implementationTags: ["guard", "damage_cap"], species: "巨人", attack: 5, health: 10 },
  { id: "GIA-M-016", nameKey: "gia_m_016_name", descriptionKey: "gia_m_016_description", type: "MINION", faction: "GIANT", rarity: "RARE", cost: 7, rune: "◆", deckLimit: 2, keywords: [], targetRule: "选择一个敌方随从", implementationTags: ["battlecry", "destroy", "attack_threshold"], species: "巨人", attack: 8, health: 7 },
  { id: "GIA-M-017", nameKey: "gia_m_017_name", descriptionKey: "gia_m_017_description", type: "MINION", faction: "GIANT", rarity: "EPIC", cost: 8, rune: "◆", deckLimit: 2, keywords: [], targetRule: "无需目标", implementationTags: ["end_turn", "hand_tribe_buff"], species: "巨人", attack: 7, health: 9 },
  { id: "GIA-M-018", nameKey: "gia_m_018_name", descriptionKey: "gia_m_018_description", type: "MINION", faction: "GIANT", rarity: "EPIC", cost: 8, rune: "◆", deckLimit: 2, keywords: ["DAMAGE"], targetRule: "无需目标", implementationTags: ["in_deck_cost_reduce", "friendly_giant_damaged", "cap_five"], species: "巨人", attack: 9, health: 8 },
  { id: "GIA-M-019", nameKey: "gia_m_019_name", descriptionKey: "gia_m_019_description", type: "MINION", faction: "GIANT", rarity: "LEGENDARY", cost: 9, rune: "◆", deckLimit: 1, keywords: ["GUARD"], targetRule: "无需目标", implementationTags: ["legendary", "guard", "battlecry", "set_min_health"], species: "巨人", attack: 7, health: 12 },
  { id: "GIA-M-020", nameKey: "gia_m_020_name", descriptionKey: "gia_m_020_description", type: "MINION", faction: "GIANT", rarity: "LEGENDARY", cost: 10, rune: "◆", deckLimit: 1, keywords: ["DAMAGE"], targetRule: "无需目标", implementationTags: ["legendary", "battlecry", "aoe_damage", "gain_per_kill"], species: "巨人", attack: 10, health: 10 },
  { id: "GEN-S-001", nameKey: "gen_s_001_name", descriptionKey: "gen_s_001_description", type: "SPELL", faction: "COMMON", rarity: "COMMON", cost: 0, rune: "✦", deckLimit: 2, keywords: ["DAMAGE"], targetRule: "选择一个随从", implementationTags: ["spell", "target_minion", "damage_reduction_once"], effect: { type: "PROTOTYPE" } },
  { id: "GEN-S-002", nameKey: "gen_s_002_name", descriptionKey: "gen_s_002_description", type: "SPELL", faction: "COMMON", rarity: "COMMON", cost: 1, rune: "✦", deckLimit: 2, keywords: ["DAMAGE", "DRAW"], targetRule: "选择一个敌方角色", implementationTags: ["spell", "damage", "conditional_cycle"], effect: { type: "DEAL_DAMAGE", amount: 1, target: "ANY_ENEMY" } },
  { id: "GEN-S-003", nameKey: "gen_s_003_name", descriptionKey: "gen_s_003_description", type: "SPELL", faction: "COMMON", rarity: "COMMON", cost: 1, rune: "✦", deckLimit: 2, keywords: ["HEAL"], targetRule: "选择一个友方角色", implementationTags: ["spell", "heal", "friendly_character"], effect: { type: "HEAL", amount: 3, target: "FRIENDLY_HERO" } },
  { id: "GEN-S-004", nameKey: "gen_s_004_name", descriptionKey: "gen_s_004_description", type: "SPELL", faction: "COMMON", rarity: "COMMON", cost: 1, rune: "✦", deckLimit: 2, keywords: ["BUFF", "GUARD"], targetRule: "选择一个友方随从", implementationTags: ["spell", "temp_attack_buff", "guard_bonus"], effect: { type: "BUFF", attack: 2, health: 0, target: "FRIENDLY_MINION" } },
  { id: "GEN-S-005", nameKey: "gen_s_005_name", descriptionKey: "gen_s_005_description", type: "SPELL", faction: "COMMON", rarity: "COMMON", cost: 2, rune: "✦", deckLimit: 2, keywords: ["DRAW"], targetRule: "无需目标", implementationTags: ["spell", "look_top", "draw_spell"], effect: { type: "DRAW_CARD", amount: 1 } },
  { id: "GEN-S-006", nameKey: "gen_s_006_name", descriptionKey: "gen_s_006_description", type: "SPELL", faction: "COMMON", rarity: "RARE", cost: 2, rune: "✦", deckLimit: 2, keywords: ["DAMAGE", "GUARD"], targetRule: "选择一个随从", implementationTags: ["spell", "damage", "guard_bonus_damage"], effect: { type: "DEAL_DAMAGE", amount: 2, target: "ANY_ENEMY" } },
  { id: "GEN-S-007", nameKey: "gen_s_007_name", descriptionKey: "gen_s_007_description", type: "SPELL", faction: "COMMON", rarity: "COMMON", cost: 2, rune: "✦", deckLimit: 2, keywords: [], targetRule: "选择一个友方随从", implementationTags: ["spell", "bounce_friendly", "cost_reduce"], effect: { type: "PROTOTYPE" } },
  { id: "GEN-S-008", nameKey: "gen_s_008_name", descriptionKey: "gen_s_008_description", type: "SPELL", faction: "COMMON", rarity: "RARE", cost: 2, rune: "✦", deckLimit: 2, keywords: ["BARRIER"], targetRule: "选择一个友方角色", implementationTags: ["spell", "temporary_shield", "expires_next_turn"], effect: { type: "BUFF", attack: 0, health: 3, target: "FRIENDLY_MINION" } },
  { id: "GEN-S-009", nameKey: "gen_s_009_name", descriptionKey: "gen_s_009_description", type: "SPELL", faction: "COMMON", rarity: "COMMON", cost: 3, rune: "✦", deckLimit: 2, keywords: ["DRAW"], targetRule: "无需目标", implementationTags: ["spell", "choose_one", "draw", "random_buff"], effect: { type: "DRAW_CARD", amount: 2 } },
  { id: "GEN-S-010", nameKey: "gen_s_010_name", descriptionKey: "gen_s_010_description", type: "SPELL", faction: "COMMON", rarity: "RARE", cost: 3, rune: "✦", deckLimit: 2, keywords: ["DRAW"], targetRule: "选择一个随从", implementationTags: ["spell", "bounce", "low_cost_compensation"], effect: { type: "PROTOTYPE" } },
  { id: "GEN-S-011", nameKey: "gen_s_011_name", descriptionKey: "gen_s_011_description", type: "SPELL", faction: "COMMON", rarity: "COMMON", cost: 3, rune: "✦", deckLimit: 2, keywords: ["HEAL", "DRAW"], targetRule: "无需目标", implementationTags: ["spell", "heal_hero", "no_friendly_attack", "draw"], effect: { type: "HEAL", amount: 5, target: "FRIENDLY_HERO" } },
  { id: "GEN-S-012", nameKey: "gen_s_012_name", descriptionKey: "gen_s_012_description", type: "SPELL", faction: "COMMON", rarity: "RARE", cost: 3, rune: "✦", deckLimit: 2, keywords: ["BUFF", "CHARGE"], targetRule: "选择一个友方随从", implementationTags: ["spell", "temp_buff", "grant_rush"], effect: { type: "BUFF", attack: 2, health: 1, target: "FRIENDLY_MINION" } },
  { id: "GEN-S-013", nameKey: "gen_s_013_name", descriptionKey: "gen_s_013_description", type: "SPELL", faction: "COMMON", rarity: "EPIC", cost: 4, rune: "✦", deckLimit: 2, keywords: [], targetRule: "选择一个随从", implementationTags: ["spell", "silence", "temp_set_attack"], effect: { type: "PROTOTYPE" } },
  { id: "GEN-S-014", nameKey: "gen_s_014_name", descriptionKey: "gen_s_014_description", type: "SPELL", faction: "COMMON", rarity: "RARE", cost: 4, rune: "✦", deckLimit: 2, keywords: ["DAMAGE"], targetRule: "选择一个敌方随从", implementationTags: ["spell", "single_target_damage"], effect: { type: "DEAL_DAMAGE", amount: 5, target: "ANY_ENEMY" } },
  { id: "GEN-S-015", nameKey: "gen_s_015_name", descriptionKey: "gen_s_015_description", type: "SPELL", faction: "COMMON", rarity: "COMMON", cost: 4, rune: "✦", deckLimit: 2, keywords: [], targetRule: "无需目标", implementationTags: ["spell", "summon_deck_copies", "stat_set_one"], effect: { type: "PROTOTYPE" } },
  { id: "GEN-S-016", nameKey: "gen_s_016_name", descriptionKey: "gen_s_016_description", type: "SPELL", faction: "COMMON", rarity: "EPIC", cost: 5, rune: "✦", deckLimit: 2, keywords: [], targetRule: "无需目标", implementationTags: ["spell", "global_debuff", "summon_sickness", "hero_power_tax"], effect: { type: "PROTOTYPE" } },
  { id: "GEN-S-017", nameKey: "gen_s_017_name", descriptionKey: "gen_s_017_description", type: "SPELL", faction: "COMMON", rarity: "RARE", cost: 5, rune: "✦", deckLimit: 2, keywords: ["HEAL", "DRAW"], targetRule: "无需目标", implementationTags: ["spell", "aoe_heal_friendly", "full_heal", "draw_cap"], effect: { type: "HEAL", amount: 3, target: "FRIENDLY_HERO" } },
  { id: "GEN-S-018", nameKey: "gen_s_018_name", descriptionKey: "gen_s_018_description", type: "SPELL", faction: "COMMON", rarity: "EPIC", cost: 6, rune: "✦", deckLimit: 2, keywords: ["DAMAGE"], targetRule: "无需目标", implementationTags: ["spell", "aoe_damage", "survivor_penalty"], effect: { type: "PROTOTYPE" } },
  { id: "GEN-S-019", nameKey: "gen_s_019_name", descriptionKey: "gen_s_019_description", type: "SPELL", faction: "COMMON", rarity: "LEGENDARY", cost: 7, rune: "✦", deckLimit: 1, keywords: ["DRAW"], targetRule: "无需目标", implementationTags: ["legendary_spell", "shuffle_hand", "redraw", "cost_reduce"], effect: { type: "DRAW_CARD", amount: 3 } },
  { id: "GEN-S-020", nameKey: "gen_s_020_name", descriptionKey: "gen_s_020_description", type: "SPELL", faction: "COMMON", rarity: "LEGENDARY", cost: 8, rune: "✦", deckLimit: 1, keywords: ["DAMAGE"], targetRule: "无需目标", implementationTags: ["legendary_spell", "choose_one", "summon_tokens", "aoe_damage", "heal_hero"], effect: { type: "HEAL", amount: 4, target: "FRIENDLY_HERO" } },
];

export const SPECIAL_BITCOIN_COIN_ID = "SPECIAL_BITCOIN_COIN";
export const SPECIAL_BITCOIN_COIN: CardDefinition = {
  id: SPECIAL_BITCOIN_COIN_ID,
  nameKey: "special_bitcoin_coin_name",
  descriptionKey: "special_bitcoin_coin_description",
  type: "SPELL",
  faction: "COMMON",
  rarity: "LEGENDARY",
  cost: 0,
  rune: "₿",
  deckLimit: 0,
  keywords: [],
  targetRule: "无需目标",
  implementationTags: ["special", "second_player_bonus", "temporary_mana"],
  effect: { type: "GAIN_TEMP_MANA", amount: 1 }
};

export const CARD_DEFINITIONS = new Map([...CARD_DATABASE, SPECIAL_BITCOIN_COIN].map((card) => [card.id, card]));
const DEFAULT_COUNTS: Readonly<Record<string, number>> = {
  "MER-M-001": 2, "MER-M-002": 2, "MER-M-003": 2, "MER-M-004": 2, "MER-M-005": 2,
  "MER-M-006": 2, "MER-M-007": 2, "MER-M-008": 2, "MER-M-009": 2, "MER-M-010": 2,
  "MER-M-011": 2, "MER-M-012": 2, "MER-M-013": 2, "MER-M-014": 2, "GEN-S-001": 2
};
export const DEFAULT_DECK_DEFINITION_IDS = Object.entries(DEFAULT_COUNTS).flatMap(([id, count]) => Array.from({ length: count }, () => id));

export function getCardDefinition(definitionId: string): CardDefinition {
  const definition = CARD_DEFINITIONS.get(definitionId);
  if (!definition) throw new Error(`Unknown card definition: ${definitionId}`);
  return definition;
}
