export type CardType = "MINION" | "SPELL";
export type GameStatus = "WAITING" | "PLAYING" | "FINISHED";
export type PlatformName = "DEVELOPMENT" | "WECHAT" | "STEAM" | "EPIC";
export type ConnectionStatus = "CONNECTING" | "CONNECTED" | "RECONNECTING" | "DISCONNECTED" | "FAILED";

export enum ErrorCode {
  NOT_YOUR_TURN = "NOT_YOUR_TURN",
  CARD_NOT_IN_HAND = "CARD_NOT_IN_HAND",
  NOT_ENOUGH_MANA = "NOT_ENOUGH_MANA",
  BOARD_FULL = "BOARD_FULL",
  INVALID_TARGET = "INVALID_TARGET",
  MINION_NOT_FOUND = "MINION_NOT_FOUND",
  MINION_CANNOT_ATTACK = "MINION_CANNOT_ATTACK",
  PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND",
  ROOM_NOT_FOUND = "ROOM_NOT_FOUND",
  ROOM_FULL = "ROOM_FULL",
  ALREADY_IN_ROOM = "ALREADY_IN_ROOM",
  NOT_IN_ROOM = "NOT_IN_ROOM",
  GAME_NOT_STARTED = "GAME_NOT_STARTED",
  GAME_ALREADY_OVER = "GAME_ALREADY_OVER",
  PLAYER_ID_MISMATCH = "PLAYER_ID_MISMATCH",
  INVALID_ACTION = "INVALID_ACTION",
  OPPONENT_DISCONNECTED = "OPPONENT_DISCONNECTED",
  INVALID_SESSION = "INVALID_SESSION",
  RECONNECT_EXPIRED = "RECONNECT_EXPIRED",
  INVALID_PAYLOAD = "INVALID_PAYLOAD",
  INVALID_DECK = "INVALID_DECK",
  RATE_LIMITED = "RATE_LIMITED",
  INTERNAL_ERROR = "INTERNAL_ERROR"
}
